site_name: AI Testbed User Guide
nav:
  - Home: index.md
  - Cerebras:
    - System Overview: cerebras/System-Overview.md
    - Getting Started: cerebras/Connect-to-a-CS-2-Node.md
    - Steps to Run a Model/Program: cerebras/Steps-to-run-a-model-or-program.md
    - Job Queuing and Submission: cerebras/Job-Queuing-and-Submission.md
    - Example Programs: cerebras/Example-Programs.md
    - Customizing environments: cerebras/Using-virtual-environments-to-customize-environment.md
    - Performance Tools: cerebras/Performance-Tools.md
    - Tunneling and Forwarding Ports: cerebras/Tunneling-and-forwarding-ports.md
    - Miscellaneous: cerebras/Miscellaneous.md
  - SambaNova:
    - System Overview: sambanova/System-Overview.md
    - Getting Started: sambanova/Logging-into-a-SambaNova-Node.md
    - Virtual Environment: sambanova/Virtual-Environment.md
    - Steps to Run a Model/Program: sambanova/Steps-to-Run-a-Model-or-Program.md
    - Job Queuing and Submission: sambanova/Job-Queuing-and-Submission.md
    - Example Programs: sambanova/Example-Programs.md
    - Tunneling and Forwarding Ports: sambanova/Tunneling-and-forwarding-ports.md
    #- DataParallel: sambanova/DataParallel.md
    - Miscellaneous: sambanova/Miscellaneous.md
    - Documentation: sambanova/Documentation.md
  # - Graphcore:
  #   - System Overview: graphcore/System-Overview.md
  #   - Getting Started: graphcore/Logging-into-a-Graphcore-Node.md
  #   - Virtual Environment: graphcore/Virtual-Environment.md
  #   - Steps to Run a Model/Program: graphcore/Steps-to-Run-a-Model-or-Program.md
  #   - Job Queuing and Submission: graphcore/Job-Queuing-and-Submission.md
  #   - Example Programs: graphcore/Example-Programs.md
  #   - Tunneling and Forwarding Ports: graphcore/Tunneling-and-forwarding-ports.md
  #   - CosmicTagger Conversion: graphcore/CosmicTagger-Conversion.md
  #   - CosmicTagger Distributed Data Parallel: graphcore/CosmicTagger-DDP.md
  #   #- DataParallel: graphcore/DataParallel.md
  #   - Miscellaneous: graphcore/Miscellaneous.md
  #   - Documentation: graphcore/Documentation.md
  - Storage: common/storage.md
  - Publication Policy: common/pub-policy.md

theme:
  name: 'material'
  custom_dir: overrides
  language: 'en'
  palette:
    scheme: alcf
  font:
    text: proxima-nova
  features:
    - tabs
    - instant
    - search.highlight
    - search.suggest
  logo: 'images/Argonne_wireframe_white_transparent.png'
  favicon: 'images/alcf_favicon.ico'

extra_css:
  - stylesheets/alcf-extra.css

extra_javascript:
  - javascripts/alcf-extra.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_name: 'argonne-lcf/ALCF-AI-Testbed'
repo_url: 'https://github.com/argonne-lcf/ALCF-AI-Testbed'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcf/ALCF-AI-Testbed'

plugins:
  - search
