site_name: AI Testbed User Guide
nav:
  - Home: README.md
  - SambaNova:
    - System Overview: sambanova/System-Overview.md
    - How to setup your base environment: sambanova/How-to-setup-your-base-environment.md
    - Using virtual environments to customize environment: sambanova/Using-virtual-environments-to-customize-environment.md
    - Steps to run a model/program: sambanova/Steps-to-run-a-model-or-program.md
    - Job Queuing and Submission: sambanova/Job-Queuing-and-Submission.md
    - Example Programs: sambanova/Example-Programs
    - Performance Tools: sambanova/Performance-Tools
    - Best Practices and FAQs: sambanova/Best-Practices-and-FAQs.md
    - Tunneling and forwarding ports: sambanova/Tunneling-and-forwarding-ports.md
    - System and Storage Policies: sambanova/System-and-Storage-Policies.md
    - Miscellaneous: sambanova/Miscellaneous.md
    - Anatomy of SambaNova PyTorch Models: sambanova/Anatomy-of-SambaNova-PyTorch-Models.md
    - DataParallel: sambanova/DataParallel.md
  - Cerebras:
    - System Overview: cerebras/System-Overview.md
    - Connect to a CS-2 node: cerebras/Connect-to-a-CS-2-node.md
    - How to setup your base environment: cerebras/How-to-setup-your-base-environment.md
    - Steps to run a model or program: cerebras/Steps-to-run-a-model-or-program.md
    - Example Programs: cerebras/Example-Programs.md
    - Job Queuing and Submission: cerebras/Job-Queuing-and-Submission.md
    - Customizing environments: cerebras/Using-virtual-environments-to-customize-environment.md
    - Performance Tools: cerebras/Performance-Tools.md
    - Best Practices and FAQs: cerebras/Best-Practices-and-FAQs.md
    - Tunneling and forwarding ports: cerebras/Tunneling-and-forwarding-ports.md
    - System and Storage Policies: cerebras/System-and-Storage-Policies.md
    - Miscellaneous: cerebras/Miscellaneous.md
